baseurl = "https://blog.qilinlou.com"
title = "Qilin Lou's Blog"
theme = "hugo-coder"
languagecode = "ch"
defaultcontentlanguage = "ch"

enableRobotsTXT = true
canonifyURLs = true

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pluralizelisttitles = false

FootnoteReturnLinkContents = "↑"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
    author = "Qilin Lou"
    info = "Code & Engineer & Consultant"
    description = "Qilin Lou's Blog"
    keywords = "blog, code, agile, and others"
    avatarurl = "images/avatar.jpg"
    logoImg = "images/favicon-16x16.png"
    header = "blog.qilinlou.com"

    github = "PhonyLou"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    hidecredits = true
    hidecopyright = false

    series = true

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    math = true
    custom_css = ["/css/main.css"]
    custom_js = ["/js/lazysizes.min.js"]

    dateFormat = "2006-01-02"

# Comments on github issue
[params.utteranc]
    repo = "PhonyLou/blog.qilinlou.com"
    issue-term = "pathname"
    theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/PhonyLou"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/qilin-lou-2764b7110/

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Practice"
            weight = 2
            url = "practice/"

            [[languages.en.menu.main]]
            name = "Code"
            weight = 3
            url = "code/"

            [[languages.en.menu.main]]
            name = "Agile"
            weight = 4
            url = "agile/"

    [languages.ch]
        languagename = "Chinese"
        title = "娄麒麟的博客"

        [languages.ch.params]
            author = "娄麒麟"
            info = "代码 & 工程实践 & 咨询"
            description = "娄师傅写字的地方"
            keywords = "blog,desenvolvedor,pessoal"

        [languages.ch.menu]

            [[languages.ch.menu.main]]
            name = "关于本人"
            weight = 1
            url = "about/"

            [[languages.ch.menu.main]]
            name = "工程实践"
            weight = 2
            url = "practice/"

            [[languages.ch.menu.main]]
            name = "代码和技术"
            weight = 3
            url = "code/"

            [[languages.ch.menu.main]]
            name = "敏捷"
            weight = 4
            url = "agile/"